server:
  port: 5000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dumbways
    username: backend
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        show_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
